// 根文件，存放操作类型
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_WEALTH_SUCCESS = 'GET_WEALTH_SUCCESS';
export const GET_POINT_SUCCESS = 'GET_POINT_SUCCESS';
export const GET_TRADEINFO_SUCCESS = 'GET_TRADEINFO_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
